# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

book_collection_by_author:
    path: "/api/books/{id:author}/collection"
    methods: ['GET']
    defaults:
        _controller: App\Controller\Api\BookController::getByAuthor
        _api_resource_class: App\Entity\Book
        _api_operation_name: book_collection
